version: '3.8'
services:
  gateway:
    build: gateway/.
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/.
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:13.7-alpine
    container_name: postgres-shareit
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

    # docker run --hostname=624588ac4dfc --mac-address=02:42:ac:11:00:02 --env=POSTGRES_DB=shareit --env=POSTGRES_USER=root --env=POSTGRES_PASSWORD=root --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=LANG=en_US.utf8 --env=PG_MAJOR=13 --env=PG_VERSION=13.7 --env=PG_SHA256=1b905bf4f3d83614a393b3c51fd345910fd261e4f5124a68d9a1fdd3a2a46399 --env=PGDATA=/var/lib/postgresql/data --volume=/var/lib/postgresql/data -p 6541:5432 --runtime=runc -d postgres:13.7-alpine