INSERT INTO USERS (user_name, EMAIL) VALUES ('user1', 'user1@email.com');
INSERT INTO USERS (user_name, EMAIL) VALUES ('user2', 'user2@email.com');
INSERT INTO USERS (user_name, EMAIL) VALUES ('user3', 'user3@email.com');

INSERT INTO REQUESTS (DESCRIPTION, REQUESTOR_ID, CREATED) VALUES ('request1 description', 2, CURRENT_TIMESTAMP);
INSERT INTO REQUESTS (DESCRIPTION, REQUESTOR_ID, CREATED) VALUES ('request2 description', 1, CURRENT_TIMESTAMP);